### ISSUE TITLE
SRFI-0

### ISSUE THREAD

**Issue by arrdem** [ox-lang/ox#30]
So Loj suggested using [SRFI-0](https://srfi.schemers.org/srfi-0/srfi-0.html) conditional expansion and features to define the `package.ox` context. This works, but it begs a couple questions:

1. How are features provided and defined? Is there a `define-feature` macro or something? Are features values, or are features simply the names of values or modules?
2. How does the hypothetical `define-feature` work with phaseless code loading? Unless features are phaseless (definition names) it really doesn't work.
3. This adds syntactic load to all `package.ox` files which doesn't really serve a purpose.

**Comment by lojikil** [comment]
`define-feature` should def be just def names, or things that have been defined ahead of time. It shouldn't be complicated, lest you head down the CL route.
